/*
Asset Components

An Asset Component is an internal part of an Asset which is defined by the Hierarchy API.  Currently the following components are supported, * Bearings * Shafts

API version: 0.1
Contact: team.gob@enlight.skf.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// GetRelatedSpeedResponseContext struct for GetRelatedSpeedResponseContext
type GetRelatedSpeedResponseContext struct {
	Id string `json:"id"`
}

// NewGetRelatedSpeedResponseContext instantiates a new GetRelatedSpeedResponseContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRelatedSpeedResponseContext(id string) *GetRelatedSpeedResponseContext {
	this := GetRelatedSpeedResponseContext{}
	this.Id = id
	return &this
}

// NewGetRelatedSpeedResponseContextWithDefaults instantiates a new GetRelatedSpeedResponseContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRelatedSpeedResponseContextWithDefaults() *GetRelatedSpeedResponseContext {
	this := GetRelatedSpeedResponseContext{}
	return &this
}

// GetId returns the Id field value
func (o *GetRelatedSpeedResponseContext) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetRelatedSpeedResponseContext) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetRelatedSpeedResponseContext) SetId(v string) {
	o.Id = v
}

func (o GetRelatedSpeedResponseContext) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableGetRelatedSpeedResponseContext struct {
	value *GetRelatedSpeedResponseContext
	isSet bool
}

func (v NullableGetRelatedSpeedResponseContext) Get() *GetRelatedSpeedResponseContext {
	return v.value
}

func (v *NullableGetRelatedSpeedResponseContext) Set(val *GetRelatedSpeedResponseContext) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRelatedSpeedResponseContext) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRelatedSpeedResponseContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRelatedSpeedResponseContext(val *GetRelatedSpeedResponseContext) *NullableGetRelatedSpeedResponseContext {
	return &NullableGetRelatedSpeedResponseContext{value: val, isSet: true}
}

func (v NullableGetRelatedSpeedResponseContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRelatedSpeedResponseContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


