/*
Asset Components

An Asset Component is an internal part of an Asset which is defined by the Hierarchy API.  Currently the following components are supported, * Bearings * Shafts

API version: 0.1
Contact: team.gob@enlight.skf.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// GetRelatedSpeedResponseFixedspeed struct for GetRelatedSpeedResponseFixedspeed
type GetRelatedSpeedResponseFixedspeed struct {
	Id string `json:"id"`
	Speed float32 `json:"speed"`
	Speedgroup string `json:"speedgroup"`
	Type string `json:"type"`
}

// NewGetRelatedSpeedResponseFixedspeed instantiates a new GetRelatedSpeedResponseFixedspeed object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRelatedSpeedResponseFixedspeed(id string, speed float32, speedgroup string, type_ string) *GetRelatedSpeedResponseFixedspeed {
	this := GetRelatedSpeedResponseFixedspeed{}
	this.Id = id
	this.Speed = speed
	this.Speedgroup = speedgroup
	this.Type = type_
	return &this
}

// NewGetRelatedSpeedResponseFixedspeedWithDefaults instantiates a new GetRelatedSpeedResponseFixedspeed object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRelatedSpeedResponseFixedspeedWithDefaults() *GetRelatedSpeedResponseFixedspeed {
	this := GetRelatedSpeedResponseFixedspeed{}
	return &this
}

// GetId returns the Id field value
func (o *GetRelatedSpeedResponseFixedspeed) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetRelatedSpeedResponseFixedspeed) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetRelatedSpeedResponseFixedspeed) SetId(v string) {
	o.Id = v
}

// GetSpeed returns the Speed field value
func (o *GetRelatedSpeedResponseFixedspeed) GetSpeed() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Speed
}

// GetSpeedOk returns a tuple with the Speed field value
// and a boolean to check if the value has been set.
func (o *GetRelatedSpeedResponseFixedspeed) GetSpeedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Speed, true
}

// SetSpeed sets field value
func (o *GetRelatedSpeedResponseFixedspeed) SetSpeed(v float32) {
	o.Speed = v
}

// GetSpeedgroup returns the Speedgroup field value
func (o *GetRelatedSpeedResponseFixedspeed) GetSpeedgroup() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Speedgroup
}

// GetSpeedgroupOk returns a tuple with the Speedgroup field value
// and a boolean to check if the value has been set.
func (o *GetRelatedSpeedResponseFixedspeed) GetSpeedgroupOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Speedgroup, true
}

// SetSpeedgroup sets field value
func (o *GetRelatedSpeedResponseFixedspeed) SetSpeedgroup(v string) {
	o.Speedgroup = v
}

// GetType returns the Type field value
func (o *GetRelatedSpeedResponseFixedspeed) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GetRelatedSpeedResponseFixedspeed) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GetRelatedSpeedResponseFixedspeed) SetType(v string) {
	o.Type = v
}

func (o GetRelatedSpeedResponseFixedspeed) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["speed"] = o.Speed
	}
	if true {
		toSerialize["speedgroup"] = o.Speedgroup
	}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableGetRelatedSpeedResponseFixedspeed struct {
	value *GetRelatedSpeedResponseFixedspeed
	isSet bool
}

func (v NullableGetRelatedSpeedResponseFixedspeed) Get() *GetRelatedSpeedResponseFixedspeed {
	return v.value
}

func (v *NullableGetRelatedSpeedResponseFixedspeed) Set(val *GetRelatedSpeedResponseFixedspeed) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRelatedSpeedResponseFixedspeed) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRelatedSpeedResponseFixedspeed) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRelatedSpeedResponseFixedspeed(val *GetRelatedSpeedResponseFixedspeed) *NullableGetRelatedSpeedResponseFixedspeed {
	return &NullableGetRelatedSpeedResponseFixedspeed{value: val, isSet: true}
}

func (v NullableGetRelatedSpeedResponseFixedspeed) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRelatedSpeedResponseFixedspeed) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


