/*
Asset Components

An Asset Component is an internal part of an Asset which is defined by the Hierarchy API.  Currently the following components are supported, * Bearings * Shafts

API version: 0.1
Contact: team.gob@enlight.skf.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// GetRelatedComponentsResponse struct for GetRelatedComponentsResponse
type GetRelatedComponentsResponse struct {
	Components []RelatedComponent `json:"components"`
	Links GetComponentRelationsResponseLinks `json:"links"`
	Context GetRelatedComponentsResponseContext `json:"context"`
}

// NewGetRelatedComponentsResponse instantiates a new GetRelatedComponentsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRelatedComponentsResponse(components []RelatedComponent, links GetComponentRelationsResponseLinks, context GetRelatedComponentsResponseContext) *GetRelatedComponentsResponse {
	this := GetRelatedComponentsResponse{}
	this.Components = components
	this.Links = links
	this.Context = context
	return &this
}

// NewGetRelatedComponentsResponseWithDefaults instantiates a new GetRelatedComponentsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRelatedComponentsResponseWithDefaults() *GetRelatedComponentsResponse {
	this := GetRelatedComponentsResponse{}
	return &this
}

// GetComponents returns the Components field value
func (o *GetRelatedComponentsResponse) GetComponents() []RelatedComponent {
	if o == nil {
		var ret []RelatedComponent
		return ret
	}

	return o.Components
}

// GetComponentsOk returns a tuple with the Components field value
// and a boolean to check if the value has been set.
func (o *GetRelatedComponentsResponse) GetComponentsOk() ([]RelatedComponent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Components, true
}

// SetComponents sets field value
func (o *GetRelatedComponentsResponse) SetComponents(v []RelatedComponent) {
	o.Components = v
}

// GetLinks returns the Links field value
func (o *GetRelatedComponentsResponse) GetLinks() GetComponentRelationsResponseLinks {
	if o == nil {
		var ret GetComponentRelationsResponseLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *GetRelatedComponentsResponse) GetLinksOk() (*GetComponentRelationsResponseLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *GetRelatedComponentsResponse) SetLinks(v GetComponentRelationsResponseLinks) {
	o.Links = v
}

// GetContext returns the Context field value
func (o *GetRelatedComponentsResponse) GetContext() GetRelatedComponentsResponseContext {
	if o == nil {
		var ret GetRelatedComponentsResponseContext
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *GetRelatedComponentsResponse) GetContextOk() (*GetRelatedComponentsResponseContext, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Context, true
}

// SetContext sets field value
func (o *GetRelatedComponentsResponse) SetContext(v GetRelatedComponentsResponseContext) {
	o.Context = v
}

func (o GetRelatedComponentsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["components"] = o.Components
	}
	if true {
		toSerialize["links"] = o.Links
	}
	if true {
		toSerialize["context"] = o.Context
	}
	return json.Marshal(toSerialize)
}

type NullableGetRelatedComponentsResponse struct {
	value *GetRelatedComponentsResponse
	isSet bool
}

func (v NullableGetRelatedComponentsResponse) Get() *GetRelatedComponentsResponse {
	return v.value
}

func (v *NullableGetRelatedComponentsResponse) Set(val *GetRelatedComponentsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRelatedComponentsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRelatedComponentsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRelatedComponentsResponse(val *GetRelatedComponentsResponse) *NullableGetRelatedComponentsResponse {
	return &NullableGetRelatedComponentsResponse{value: val, isSet: true}
}

func (v NullableGetRelatedComponentsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRelatedComponentsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


