/*
Asset Components

An Asset Component is an internal part of an Asset which is defined by the Hierarchy API.  Currently the following components are supported, * Bearings * Shafts

API version: 0.1
Contact: team.gob@enlight.skf.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// GetComponentResponse struct for GetComponentResponse
type GetComponentResponse struct {
	// Unique identifier for a component
	Id *string `json:"id,omitempty"`
	// Hierarchy Asset ID where this component is located within
	Asset string `json:"asset"`
	// Identifier to the component that this one is attached to, required for bearings
	AttachedTo *string `json:"attachedTo,omitempty"`
	// What kind of component it is. Will decide what other attributes can be used.
	Type string `json:"type"`
	// A non unique identifier within the asset to help locate the component
	Position int32 `json:"position"`
	Origin *Origin `json:"origin,omitempty"`
	// The fixed rotation speed of the shaft, expressed in RPM
	FixedSpeed *float64 `json:"fixedSpeed,omitempty"`
	// A human-readable description of where the bearing is located
	PositionDescription *string `json:"positionDescription,omitempty"`
	// Bearing model number
	Designation *string `json:"designation,omitempty"`
	// Who is producing the bearing, usually a company name
	Manufacturer *string `json:"manufacturer,omitempty"`
	// A manufacturer designated identifier for a specific bearing
	SerialNumber *string `json:"serialNumber,omitempty"`
	// Indicating what ring or rings that is rotating under operating conditions
	RotatingRing *string `json:"rotatingRing,omitempty"`
	// What side of the shaft the bearing is mounted
	ShaftSide *string `json:"shaftSide,omitempty"`
}

// NewGetComponentResponse instantiates a new GetComponentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetComponentResponse(asset string, type_ string, position int32) *GetComponentResponse {
	this := GetComponentResponse{}
	this.Asset = asset
	this.Type = type_
	this.Position = position
	return &this
}

// NewGetComponentResponseWithDefaults instantiates a new GetComponentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetComponentResponseWithDefaults() *GetComponentResponse {
	this := GetComponentResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetComponentResponse) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetComponentResponse) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetComponentResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetComponentResponse) SetId(v string) {
	o.Id = &v
}

// GetAsset returns the Asset field value
func (o *GetComponentResponse) GetAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *GetComponentResponse) GetAssetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *GetComponentResponse) SetAsset(v string) {
	o.Asset = v
}

// GetAttachedTo returns the AttachedTo field value if set, zero value otherwise.
func (o *GetComponentResponse) GetAttachedTo() string {
	if o == nil || o.AttachedTo == nil {
		var ret string
		return ret
	}
	return *o.AttachedTo
}

// GetAttachedToOk returns a tuple with the AttachedTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetComponentResponse) GetAttachedToOk() (*string, bool) {
	if o == nil || o.AttachedTo == nil {
		return nil, false
	}
	return o.AttachedTo, true
}

// HasAttachedTo returns a boolean if a field has been set.
func (o *GetComponentResponse) HasAttachedTo() bool {
	if o != nil && o.AttachedTo != nil {
		return true
	}

	return false
}

// SetAttachedTo gets a reference to the given string and assigns it to the AttachedTo field.
func (o *GetComponentResponse) SetAttachedTo(v string) {
	o.AttachedTo = &v
}

// GetType returns the Type field value
func (o *GetComponentResponse) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GetComponentResponse) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GetComponentResponse) SetType(v string) {
	o.Type = v
}

// GetPosition returns the Position field value
func (o *GetComponentResponse) GetPosition() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Position
}

// GetPositionOk returns a tuple with the Position field value
// and a boolean to check if the value has been set.
func (o *GetComponentResponse) GetPositionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Position, true
}

// SetPosition sets field value
func (o *GetComponentResponse) SetPosition(v int32) {
	o.Position = v
}

// GetOrigin returns the Origin field value if set, zero value otherwise.
func (o *GetComponentResponse) GetOrigin() Origin {
	if o == nil || o.Origin == nil {
		var ret Origin
		return ret
	}
	return *o.Origin
}

// GetOriginOk returns a tuple with the Origin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetComponentResponse) GetOriginOk() (*Origin, bool) {
	if o == nil || o.Origin == nil {
		return nil, false
	}
	return o.Origin, true
}

// HasOrigin returns a boolean if a field has been set.
func (o *GetComponentResponse) HasOrigin() bool {
	if o != nil && o.Origin != nil {
		return true
	}

	return false
}

// SetOrigin gets a reference to the given Origin and assigns it to the Origin field.
func (o *GetComponentResponse) SetOrigin(v Origin) {
	o.Origin = &v
}

// GetFixedSpeed returns the FixedSpeed field value if set, zero value otherwise.
func (o *GetComponentResponse) GetFixedSpeed() float64 {
	if o == nil || o.FixedSpeed == nil {
		var ret float64
		return ret
	}
	return *o.FixedSpeed
}

// GetFixedSpeedOk returns a tuple with the FixedSpeed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetComponentResponse) GetFixedSpeedOk() (*float64, bool) {
	if o == nil || o.FixedSpeed == nil {
		return nil, false
	}
	return o.FixedSpeed, true
}

// HasFixedSpeed returns a boolean if a field has been set.
func (o *GetComponentResponse) HasFixedSpeed() bool {
	if o != nil && o.FixedSpeed != nil {
		return true
	}

	return false
}

// SetFixedSpeed gets a reference to the given float64 and assigns it to the FixedSpeed field.
func (o *GetComponentResponse) SetFixedSpeed(v float64) {
	o.FixedSpeed = &v
}

// GetPositionDescription returns the PositionDescription field value if set, zero value otherwise.
func (o *GetComponentResponse) GetPositionDescription() string {
	if o == nil || o.PositionDescription == nil {
		var ret string
		return ret
	}
	return *o.PositionDescription
}

// GetPositionDescriptionOk returns a tuple with the PositionDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetComponentResponse) GetPositionDescriptionOk() (*string, bool) {
	if o == nil || o.PositionDescription == nil {
		return nil, false
	}
	return o.PositionDescription, true
}

// HasPositionDescription returns a boolean if a field has been set.
func (o *GetComponentResponse) HasPositionDescription() bool {
	if o != nil && o.PositionDescription != nil {
		return true
	}

	return false
}

// SetPositionDescription gets a reference to the given string and assigns it to the PositionDescription field.
func (o *GetComponentResponse) SetPositionDescription(v string) {
	o.PositionDescription = &v
}

// GetDesignation returns the Designation field value if set, zero value otherwise.
func (o *GetComponentResponse) GetDesignation() string {
	if o == nil || o.Designation == nil {
		var ret string
		return ret
	}
	return *o.Designation
}

// GetDesignationOk returns a tuple with the Designation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetComponentResponse) GetDesignationOk() (*string, bool) {
	if o == nil || o.Designation == nil {
		return nil, false
	}
	return o.Designation, true
}

// HasDesignation returns a boolean if a field has been set.
func (o *GetComponentResponse) HasDesignation() bool {
	if o != nil && o.Designation != nil {
		return true
	}

	return false
}

// SetDesignation gets a reference to the given string and assigns it to the Designation field.
func (o *GetComponentResponse) SetDesignation(v string) {
	o.Designation = &v
}

// GetManufacturer returns the Manufacturer field value if set, zero value otherwise.
func (o *GetComponentResponse) GetManufacturer() string {
	if o == nil || o.Manufacturer == nil {
		var ret string
		return ret
	}
	return *o.Manufacturer
}

// GetManufacturerOk returns a tuple with the Manufacturer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetComponentResponse) GetManufacturerOk() (*string, bool) {
	if o == nil || o.Manufacturer == nil {
		return nil, false
	}
	return o.Manufacturer, true
}

// HasManufacturer returns a boolean if a field has been set.
func (o *GetComponentResponse) HasManufacturer() bool {
	if o != nil && o.Manufacturer != nil {
		return true
	}

	return false
}

// SetManufacturer gets a reference to the given string and assigns it to the Manufacturer field.
func (o *GetComponentResponse) SetManufacturer(v string) {
	o.Manufacturer = &v
}

// GetSerialNumber returns the SerialNumber field value if set, zero value otherwise.
func (o *GetComponentResponse) GetSerialNumber() string {
	if o == nil || o.SerialNumber == nil {
		var ret string
		return ret
	}
	return *o.SerialNumber
}

// GetSerialNumberOk returns a tuple with the SerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetComponentResponse) GetSerialNumberOk() (*string, bool) {
	if o == nil || o.SerialNumber == nil {
		return nil, false
	}
	return o.SerialNumber, true
}

// HasSerialNumber returns a boolean if a field has been set.
func (o *GetComponentResponse) HasSerialNumber() bool {
	if o != nil && o.SerialNumber != nil {
		return true
	}

	return false
}

// SetSerialNumber gets a reference to the given string and assigns it to the SerialNumber field.
func (o *GetComponentResponse) SetSerialNumber(v string) {
	o.SerialNumber = &v
}

// GetRotatingRing returns the RotatingRing field value if set, zero value otherwise.
func (o *GetComponentResponse) GetRotatingRing() string {
	if o == nil || o.RotatingRing == nil {
		var ret string
		return ret
	}
	return *o.RotatingRing
}

// GetRotatingRingOk returns a tuple with the RotatingRing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetComponentResponse) GetRotatingRingOk() (*string, bool) {
	if o == nil || o.RotatingRing == nil {
		return nil, false
	}
	return o.RotatingRing, true
}

// HasRotatingRing returns a boolean if a field has been set.
func (o *GetComponentResponse) HasRotatingRing() bool {
	if o != nil && o.RotatingRing != nil {
		return true
	}

	return false
}

// SetRotatingRing gets a reference to the given string and assigns it to the RotatingRing field.
func (o *GetComponentResponse) SetRotatingRing(v string) {
	o.RotatingRing = &v
}

// GetShaftSide returns the ShaftSide field value if set, zero value otherwise.
func (o *GetComponentResponse) GetShaftSide() string {
	if o == nil || o.ShaftSide == nil {
		var ret string
		return ret
	}
	return *o.ShaftSide
}

// GetShaftSideOk returns a tuple with the ShaftSide field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetComponentResponse) GetShaftSideOk() (*string, bool) {
	if o == nil || o.ShaftSide == nil {
		return nil, false
	}
	return o.ShaftSide, true
}

// HasShaftSide returns a boolean if a field has been set.
func (o *GetComponentResponse) HasShaftSide() bool {
	if o != nil && o.ShaftSide != nil {
		return true
	}

	return false
}

// SetShaftSide gets a reference to the given string and assigns it to the ShaftSide field.
func (o *GetComponentResponse) SetShaftSide(v string) {
	o.ShaftSide = &v
}

func (o GetComponentResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["asset"] = o.Asset
	}
	if o.AttachedTo != nil {
		toSerialize["attachedTo"] = o.AttachedTo
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["position"] = o.Position
	}
	if o.Origin != nil {
		toSerialize["origin"] = o.Origin
	}
	if o.FixedSpeed != nil {
		toSerialize["fixedSpeed"] = o.FixedSpeed
	}
	if o.PositionDescription != nil {
		toSerialize["positionDescription"] = o.PositionDescription
	}
	if o.Designation != nil {
		toSerialize["designation"] = o.Designation
	}
	if o.Manufacturer != nil {
		toSerialize["manufacturer"] = o.Manufacturer
	}
	if o.SerialNumber != nil {
		toSerialize["serialNumber"] = o.SerialNumber
	}
	if o.RotatingRing != nil {
		toSerialize["rotatingRing"] = o.RotatingRing
	}
	if o.ShaftSide != nil {
		toSerialize["shaftSide"] = o.ShaftSide
	}
	return json.Marshal(toSerialize)
}

type NullableGetComponentResponse struct {
	value *GetComponentResponse
	isSet bool
}

func (v NullableGetComponentResponse) Get() *GetComponentResponse {
	return v.value
}

func (v *NullableGetComponentResponse) Set(val *GetComponentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetComponentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetComponentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetComponentResponse(val *GetComponentResponse) *NullableGetComponentResponse {
	return &NullableGetComponentResponse{value: val, isSet: true}
}

func (v NullableGetComponentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetComponentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


