/*
Asset Components

An Asset Component is an internal part of an Asset which is defined by the Hierarchy API.  Currently the following components are supported, * Bearings * Shafts

API version: 0.1
Contact: team.gob@enlight.skf.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// GetComponentByOriginResponse struct for GetComponentByOriginResponse
type GetComponentByOriginResponse struct {
	// The unique identifier for a component that has the specified origin
	Id string `json:"id"`
}

// NewGetComponentByOriginResponse instantiates a new GetComponentByOriginResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetComponentByOriginResponse(id string) *GetComponentByOriginResponse {
	this := GetComponentByOriginResponse{}
	this.Id = id
	return &this
}

// NewGetComponentByOriginResponseWithDefaults instantiates a new GetComponentByOriginResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetComponentByOriginResponseWithDefaults() *GetComponentByOriginResponse {
	this := GetComponentByOriginResponse{}
	return &this
}

// GetId returns the Id field value
func (o *GetComponentByOriginResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetComponentByOriginResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetComponentByOriginResponse) SetId(v string) {
	o.Id = v
}

func (o GetComponentByOriginResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableGetComponentByOriginResponse struct {
	value *GetComponentByOriginResponse
	isSet bool
}

func (v NullableGetComponentByOriginResponse) Get() *GetComponentByOriginResponse {
	return v.value
}

func (v *NullableGetComponentByOriginResponse) Set(val *GetComponentByOriginResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetComponentByOriginResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetComponentByOriginResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetComponentByOriginResponse(val *GetComponentByOriginResponse) *NullableGetComponentByOriginResponse {
	return &NullableGetComponentByOriginResponse{value: val, isSet: true}
}

func (v NullableGetComponentByOriginResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetComponentByOriginResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


