/*
Asset Components

An Asset Component is an internal part of an Asset which is defined by the Hierarchy API.  Currently the following components are supported, * Bearings * Shafts

API version: 0.1
Contact: team.gob@enlight.skf.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// GetAssetComponentsResponse struct for GetAssetComponentsResponse
type GetAssetComponentsResponse struct {
	Components []Component `json:"components,omitempty"`
	Count *int32 `json:"count,omitempty"`
}

// NewGetAssetComponentsResponse instantiates a new GetAssetComponentsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAssetComponentsResponse() *GetAssetComponentsResponse {
	this := GetAssetComponentsResponse{}
	return &this
}

// NewGetAssetComponentsResponseWithDefaults instantiates a new GetAssetComponentsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAssetComponentsResponseWithDefaults() *GetAssetComponentsResponse {
	this := GetAssetComponentsResponse{}
	return &this
}

// GetComponents returns the Components field value if set, zero value otherwise.
func (o *GetAssetComponentsResponse) GetComponents() []Component {
	if o == nil || o.Components == nil {
		var ret []Component
		return ret
	}
	return o.Components
}

// GetComponentsOk returns a tuple with the Components field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAssetComponentsResponse) GetComponentsOk() ([]Component, bool) {
	if o == nil || o.Components == nil {
		return nil, false
	}
	return o.Components, true
}

// HasComponents returns a boolean if a field has been set.
func (o *GetAssetComponentsResponse) HasComponents() bool {
	if o != nil && o.Components != nil {
		return true
	}

	return false
}

// SetComponents gets a reference to the given []Component and assigns it to the Components field.
func (o *GetAssetComponentsResponse) SetComponents(v []Component) {
	o.Components = v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *GetAssetComponentsResponse) GetCount() int32 {
	if o == nil || o.Count == nil {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAssetComponentsResponse) GetCountOk() (*int32, bool) {
	if o == nil || o.Count == nil {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *GetAssetComponentsResponse) HasCount() bool {
	if o != nil && o.Count != nil {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *GetAssetComponentsResponse) SetCount(v int32) {
	o.Count = &v
}

func (o GetAssetComponentsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Components != nil {
		toSerialize["components"] = o.Components
	}
	if o.Count != nil {
		toSerialize["count"] = o.Count
	}
	return json.Marshal(toSerialize)
}

type NullableGetAssetComponentsResponse struct {
	value *GetAssetComponentsResponse
	isSet bool
}

func (v NullableGetAssetComponentsResponse) Get() *GetAssetComponentsResponse {
	return v.value
}

func (v *NullableGetAssetComponentsResponse) Set(val *GetAssetComponentsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAssetComponentsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAssetComponentsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAssetComponentsResponse(val *GetAssetComponentsResponse) *NullableGetAssetComponentsResponse {
	return &NullableGetAssetComponentsResponse{value: val, isSet: true}
}

func (v NullableGetAssetComponentsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAssetComponentsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


