/*
Asset Components

An Asset Component is an internal part of an Asset which is defined by the Hierarchy API.  Currently the following components are supported, * Bearings * Shafts

API version: 0.1
Contact: team.gob@enlight.skf.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// SetComponentSpeedRequest struct for SetComponentSpeedRequest
type SetComponentSpeedRequest struct {
	Configuration SpeedConfiguration `json:"configuration"`
}

// NewSetComponentSpeedRequest instantiates a new SetComponentSpeedRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetComponentSpeedRequest(configuration SpeedConfiguration) *SetComponentSpeedRequest {
	this := SetComponentSpeedRequest{}
	this.Configuration = configuration
	return &this
}

// NewSetComponentSpeedRequestWithDefaults instantiates a new SetComponentSpeedRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetComponentSpeedRequestWithDefaults() *SetComponentSpeedRequest {
	this := SetComponentSpeedRequest{}
	return &this
}

// GetConfiguration returns the Configuration field value
func (o *SetComponentSpeedRequest) GetConfiguration() SpeedConfiguration {
	if o == nil {
		var ret SpeedConfiguration
		return ret
	}

	return o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value
// and a boolean to check if the value has been set.
func (o *SetComponentSpeedRequest) GetConfigurationOk() (*SpeedConfiguration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Configuration, true
}

// SetConfiguration sets field value
func (o *SetComponentSpeedRequest) SetConfiguration(v SpeedConfiguration) {
	o.Configuration = v
}

func (o SetComponentSpeedRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["configuration"] = o.Configuration
	}
	return json.Marshal(toSerialize)
}

type NullableSetComponentSpeedRequest struct {
	value *SetComponentSpeedRequest
	isSet bool
}

func (v NullableSetComponentSpeedRequest) Get() *SetComponentSpeedRequest {
	return v.value
}

func (v *NullableSetComponentSpeedRequest) Set(val *SetComponentSpeedRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetComponentSpeedRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetComponentSpeedRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetComponentSpeedRequest(val *SetComponentSpeedRequest) *NullableSetComponentSpeedRequest {
	return &NullableSetComponentSpeedRequest{value: val, isSet: true}
}

func (v NullableSetComponentSpeedRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetComponentSpeedRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


