/*
Asset Components

An Asset Component is an internal part of an Asset which is defined by the Hierarchy API.  Currently the following components are supported, * Bearings * Shafts

API version: 0.1
Contact: team.gob@enlight.skf.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// PutComponentSpeedResponse struct for PutComponentSpeedResponse
type PutComponentSpeedResponse struct {
	Calculated CalculatedSpeed `json:"calculated"`
	Configuration SpeedConfiguration `json:"configuration"`
}

// NewPutComponentSpeedResponse instantiates a new PutComponentSpeedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutComponentSpeedResponse(calculated CalculatedSpeed, configuration SpeedConfiguration) *PutComponentSpeedResponse {
	this := PutComponentSpeedResponse{}
	this.Calculated = calculated
	this.Configuration = configuration
	return &this
}

// NewPutComponentSpeedResponseWithDefaults instantiates a new PutComponentSpeedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutComponentSpeedResponseWithDefaults() *PutComponentSpeedResponse {
	this := PutComponentSpeedResponse{}
	return &this
}

// GetCalculated returns the Calculated field value
func (o *PutComponentSpeedResponse) GetCalculated() CalculatedSpeed {
	if o == nil {
		var ret CalculatedSpeed
		return ret
	}

	return o.Calculated
}

// GetCalculatedOk returns a tuple with the Calculated field value
// and a boolean to check if the value has been set.
func (o *PutComponentSpeedResponse) GetCalculatedOk() (*CalculatedSpeed, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Calculated, true
}

// SetCalculated sets field value
func (o *PutComponentSpeedResponse) SetCalculated(v CalculatedSpeed) {
	o.Calculated = v
}

// GetConfiguration returns the Configuration field value
func (o *PutComponentSpeedResponse) GetConfiguration() SpeedConfiguration {
	if o == nil {
		var ret SpeedConfiguration
		return ret
	}

	return o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value
// and a boolean to check if the value has been set.
func (o *PutComponentSpeedResponse) GetConfigurationOk() (*SpeedConfiguration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Configuration, true
}

// SetConfiguration sets field value
func (o *PutComponentSpeedResponse) SetConfiguration(v SpeedConfiguration) {
	o.Configuration = v
}

func (o PutComponentSpeedResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["calculated"] = o.Calculated
	}
	if true {
		toSerialize["configuration"] = o.Configuration
	}
	return json.Marshal(toSerialize)
}

type NullablePutComponentSpeedResponse struct {
	value *PutComponentSpeedResponse
	isSet bool
}

func (v NullablePutComponentSpeedResponse) Get() *PutComponentSpeedResponse {
	return v.value
}

func (v *NullablePutComponentSpeedResponse) Set(val *PutComponentSpeedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePutComponentSpeedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePutComponentSpeedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutComponentSpeedResponse(val *PutComponentSpeedResponse) *NullablePutComponentSpeedResponse {
	return &NullablePutComponentSpeedResponse{value: val, isSet: true}
}

func (v NullablePutComponentSpeedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutComponentSpeedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


